[env:nano]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3

lib_deps =
  olikraus/U8g2@^2.36.5
  adafruit/RTClib@^2.1.4
  ArduinoJson
