[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM4
monitor_port = COM4

lib_deps =
  ArduinoJson
  ESP8266WebServer
